config/routes.rb
Rails.application.routes.draw do
  get :download_file, to: 'documents#download_file'
  resources :documents

  devise_for :users
  root to: 'documents#index'
end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :user

  mount_uploader :file, FileUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :documents

  def to_s
    email
  end

  def is_admin?
    email == 'hi@joaonetto.me'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  ensure_security_headers # See more: https://github.com/twitter/secureheaders

end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  before_action :restrict_access, only: [:edit, :update, :destroy, :new, :create]

  # GET /documents
  # GET /documents.json
  def index
    @documents = user_documents.all
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = user_documents.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = user_documents.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def download_file
    @document = user_documents.find(params[:id])
    send_file(@document.file.path,
      :disposition => 'attachment',
      :url_based_filename => false)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = user_documents.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:user_id, :file)
    end

    def user_documents
      if current_user.email == 'hi@joaonetto.me'
        Document
      else
        current_user.documents
      end
    end

    def restrict_access
      return if current_user.is_admin?
      flash[:error] = 'You don\'t have permission.'
      redirect_to documents_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_flash_messages.html.slim
- if flash[:warn] || flash[:alert]
  .alert.alert-warning #{flash[:warn]} #{flash[:alert]}
- if flash[:notice] || flash[:success]
  .alert.alert-success #{flash[:notice]} #{flash[:success]}
- if flash[:info]
  .alert.alert-info #{flash[:info]}
- if flash[:error]
  .alert.alert-danger #{flash[:error]}

app/views/application/_navigation.html.slim
nav.navbar.navbar-default role="navigation"
  .container-fluid
    /! Brand and toggle get grouped for better mobile display
    .navbar-header
      button.navbar-toggle data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.navbar-brand href="/" ODONTO
    /! Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        li
          -if user_signed_in?
            = link_to('Logout', destroy_user_session_path, :method => :delete)
          - else
             = link_to('Login', new_user_session_path)
    /! /.navbar-collapse
  /! /.container-fluid

app/views/documents/_form.html.slim
= simple_form_for(@document, html: { multipart: true, class: '' }) do |f|
  = f.error_notification

  br/

  .form-group
    = f.association :user, label_html: { class: 'control-label'}, input_html: { class: 'form-control input-lg'}

  br/

  .form-group
    = f.input :file
    = f.hidden_field :file_cache

  br/

  .form-actions
    = f.button :submit, class: 'btn btn-success'

app/views/documents/edit.html.slim
h1.page-header Editing document

== render 'form'

br/
br/
hr/
= link_to 'Back', documents_path, class: 'btn btn-info'

app/views/documents/index.html.slim
h1.page-header
  'My Documents
  - if current_user.is_admin?
    = link_to 'Upload File', new_document_path, class: 'btn btn-success btn-sm'

table.table.table-striped.table-responsive
  thead
    tr
      - if current_user.is_admin?
        th User Email
      th Document
      - if current_user.is_admin?
        th

  tbody
    - @documents.each do |document|
      tr
        - if current_user.is_admin?
          td = document.user
        td = link_to document.file, document
        - if current_user.is_admin?
          td.text-right
            .btn-group
              = link_to 'Edit', edit_document_path(document), class: 'btn btn-primary'
              = link_to raw('<span class="glyphicon glyphicon-remove"></span>'), document, data: {:confirm => 'Are you sure?'}, :method => :delete, class: 'btn btn-danger'

app/views/documents/new.html.slim
h1.page-header Upload document

== render 'form'

br/
br/
hr/
= link_to 'Back', documents_path, class: 'btn btn-info'

app/views/documents/show.html.slim
h1.page-header
  | Document

- if current_user.is_admin?
  p.lead
    h4 User
    = @document.user

p.lead
  h4 File:
  = @document.file

br/
br/

p
  = link_to raw('<span class=" glyphicon glyphicon-floppy-save"></span> Baixar Arquivo'), download_file_path(id: @document.id), class: 'btn btn-success btn-lg'

br/
br/
hr/

- if current_user.is_admin?
  = link_to 'Edit', edit_document_path(@document), class: 'btn btn-primary'
  ' &nbsp;
= link_to 'Back', documents_path, class: 'btn btn-info'

app/views/layouts/application.html.slim
doctype 5
html lang="en"
  head
    meta charset="utf-8"
    meta name="keywords" content=""
    meta name="description" content=""

    title
      = page_title(app_name: 'ODONTO-FILES')

    link href="/favicon.ico" rel=("shortcut icon")

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

    /![if lt IE 9]
      script src="http://html5shim.googlecode.com/svn/trunk/html5.js"

  body class=body_class
    = render 'navigation'

    .container
      = render 'flash_messages'

      = yield